# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='type_profil',
        ),
        migrations.AddField(
            model_name='profil',
            name='is_auteur_profil',
            field=models.BooleanField(default=True, verbose_name='Est un auteur'),
        ),
        migrations.AddField(
            model_name='profil',
            name='is_evaluateur_profil',
            field=models.BooleanField(default=False, verbose_name='Est un évaluateur'),
        ),
        migrations.AddField(
            model_name='profil',
            name='is_financeur_profil',
            field=models.BooleanField(default=False, verbose_name='Est un financeur'),
        ),
    ]
