# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0002_auto_20190121_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='is_evaluateur_profil',
            field=models.BooleanField(default=False, verbose_name=b'Est un \xc3\xa9valuateur'),
        ),
    ]
