# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeOurPlanetGreatAgain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_projet', models.CharField(max_length=40, verbose_name='titre ')),
                ('description_projet', models.CharField(max_length=400, verbose_name='description ')),
                ('objectif_collecte_projet', models.IntegerField(verbose_name='Objectif de la collecte')),
            ],
        ),
    ]
