# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeOurPlanetGreatAgain', '0003_delete_projet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auteur',
        ),
    ]
