# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
        ('projets', '0003_auto_20181206_2325'),
    ]

    operations = [
        #migrations.RemoveField(
         #   model_name='projet',
         #   name='objectif_collecte_projet',
        #),
        migrations.AddField(
            model_name='projet',
            name='auteur_projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='profils.Profil'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_ajout_projet',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'ajout"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='finance_projet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Financement requis'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description_projet',
            field=models.CharField(max_length=400, verbose_name='Description '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre_projet',
            field=models.CharField(max_length=40, verbose_name='Titre du projet '),
        ),
    ]
