# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_auto_20181207_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='auteur_projet',
        ),
        migrations.DeleteModel(
            name='projet',
        ),
    ]
