# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profils', '0001_initial'),
        ('projets', '0005_auto_20190113_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_projet', models.CharField(max_length=40, verbose_name='Titre du projet ')),
                ('description_projet', models.TextField(max_length=4000, verbose_name='Description ')),
                ('date_ajout_projet', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('finance_cumul_projet', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Financement collecté')),
                ('finance_total_projet', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Financement requis')),
                ('auteur_projet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='profils.Profil')),
            ],
        ),
    ]
