# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description_projet',
            field=models.TextField(blank=True, max_length=4000, verbose_name='Description '),
        ),
    ]
