# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 09:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0007_auto_20190113_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=255, verbose_name='Commentaire ')),
                ('note_evaluation', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Note du projet')),
                ('evaluateur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_finance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Montant ')),
                ('date_finance', models.DateTimeField(auto_now_add=True, verbose_name='Date du don')),
                ('financeur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='financeur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='projet',
            name='finance_cumul_projet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='finance_total_projet',
        ),
        migrations.AddField(
            model_name='financement',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projet_finance', to='projets.Projet'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projet_eval', to='projets.Projet'),
        ),
    ]
