# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
        ('projets', '0010_auto_20190114_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='auteur_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='profil_projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='p_auteur', to='profils.Profil'),
        ),
    ]
