# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0016_auto_20190118_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_acquis_finance',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date aquisition financement'),
        ),
        migrations.AddField(
            model_name='projet',
            name='financement_est_aquis',
            field=models.BooleanField(default=False, verbose_name='Financement déjà acquis'),
        ),
    ]
