# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0011_auto_20190114_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='profil_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='auteur_projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
