# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0012_auto_20190114_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='date_evaluation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'évaluation"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projets.Projet'),
        ),
        migrations.AlterField(
            model_name='financement',
            name='financeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financement',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projets.Projet'),
        ),
    ]
