# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0015_projet_finance_requis_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financement',
            name='montant_finance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='finance_requis_projet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Financement réquis'),
        ),
    ]
