# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0018_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='like_authenticate_user',
        ),
    ]
