# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 23:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0019_auto_20190122_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='note_evaluation',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Note du projet'),
        ),
    ]
