# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0020_auto_20190123_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='date_evaluation',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b"Date d'\xc3\xa9valuation"),
        ),
        migrations.AlterField(
            model_name='like',
            name='date_like',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b"Date d'\xc3\xa9valuation"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='finance_requis_projet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Financement r\xc3\xa9quis'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='financement_est_aquis',
            field=models.BooleanField(default=False, verbose_name=b'Financement d\xc3\xa9j\xc3\xa0 acquis'),
        ),
    ]
